### ISSUE TITLE
Discounted orders are off by 1c

### ISSUE THREAD

**Issue by alexanderkladov** [simplifycom/woocommerce-simplify-payment-gateway-plugin#7]
Hi,

I have recently encountered an issue, which I think is related to this plugin. I received an order, which had a subtotal of $179.6 + 10% discount. So what should've been charged via Simplify is $161.64, but $161.63 was charged instead, which is -1c from the correct amount.

What's strange is that WooCommerce is displaying the correct price in backend (see screenshot below)

![WooCommerce Order Cost Calculations](https://user-images.githubusercontent.com/1500893/47330981-19d50d00-d62f-11e8-836b-ee045e279c07.png)

While Simplify is showing $161.63, meaning that the customer was charged 1c less (see below)

![Simplify charges](https://user-images.githubusercontent.com/1500893/47331114-abdd1580-d62f-11e8-8653-664ee91bcd2d.png)

Can you please investigate why that happened?

Regards,
Alex

**Comment by Johnnerz** [comment]
Hi Alex,

We are looking into this issue and will let you know when we get to the root cause of this.

John

**Comment by alexanderkladov** [comment]
Hi John,

Thanks for your response. I can see that you have made some updates in regards to this issue & released [v1.4.3](https://github.com/simplifycom/woocommerce-simplify-payment-gateway-plugin/raw/master/dist/simplifycommerce-1.4.3.zip). Is this resolved now?

Also, how can I update this plugin in WordPress? Or even better - setup notifications in WordPress dashboard, so that I would be notified when new updates are released (just like any other regular plugin).

Regards,
Alex

**Comment by Johnnerz** [comment]
Hi Alex,

We have just published that release now.

The way you can update this, is by deactivating and then deleting the current plugin, then installing the new one by uploading the zip file you have downloaded from this page. Please keep note of your API keys, just in case they get wiped in the uninstall. 

With regards to automatic updates through the front-end, it is something we are looking into and hope to have in place in the new year.

**Comment by tychobrailleur** [comment]
@alexanderkladov Are you still experiencing the issue with the updated plugin?  Can this issue be closed?

**Comment by alexanderkladov** [comment]
@tychobrailleur So far we've only had that happen once, so it might take a while for the error to re-appear again, if it wasn't resolved. But rounding the amount have most likely resolved the issue.

I will keep an eye on this, but for now we can probably close this.

Also, minor note, you forgot to update the version number from 1.4.2 to 1.4.3, so the plugin still looks like as if it hasn't been updated in WP backend.
